static_resources:
  listeners:
    - name: jwks_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 15010
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: jwks_proxy
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: kubernetes
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: kubernetes }
                http_filters:
                  - name: envoy.filters.http.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      inline_code: |
                        function envoy_on_request(req)
                          local f = io.open("/var/run/secrets/kubernetes.io/serviceaccount/token", "r")
                          if f then
                            local token = f:read("*a")
                            f:close()
                            req:headers():add("Authorization", "Bearer " .. token)
                          end
                        end
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: kubernetes
      type: STRICT_DNS
      connect_timeout: 1s
      lb_policy: ROUND_ROBIN
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: kubernetes
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: kubernetes.default.svc.cluster.local
                      port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            validation_context:
              trusted_ca:
                filename: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          sni: kubernetes.default.svc.cluster.local
