apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: zero-secret
    envs:
      - .env.secret
configMapGenerator:
  - name: zero-cache-envoy-config
    files:
      - envoy.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - deployment.yaml
